keys:
  - &admin age12xun002hsrjal5gpdms39h0pawpda9qkhfjt78jgaxrww49dsf8sdljsdu

creation_rules:
  - path_regex: ^infra[/\\]secrets[/\\].*$
    key_groups:
      - age:
          - *admin
  - path_regex: ^infra[/\\]terraform[/\\]grafana-stack[/\\]terraform\.tfvars(\.encrypted)?$
    key_groups:
      - age:
          - *admin
  - path_regex: ^infra[/\\]ansible[/\\]group_vars[/\\].*\.yml(\.encrypted)?$
    key_groups:
      - age:
          - *admin
